"""add code, is_public and is_active to surveys table

Revision ID: 018e64afb4d4
Revises: 53c63f7c21d7
Create Date: 2026-07-18 17:39:34.567625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018e64afb4d4'
down_revision: Union[str, Sequence[str], None] = '53c63f7c21d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('code', sa.String(length=10), nullable=False))
    op.add_column('surveys', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'surveys', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='unique')
    op.drop_column('surveys', 'is_public')
    op.drop_column('surveys', 'code')
    # ### end Alembic commands ###
