"""add survey_members table

Revision ID: 53c63f7c21d7
Revises: 972cb02d0a10
Create Date: 2026-07-14 09:42:13.724046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c63f7c21d7'
down_revision: Union[str, Sequence[str], None] = '972cb02d0a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_members',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='memberrole'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_id', 'user_id')
    )
    op.drop_constraint(op.f('surveys_user_id_fkey'), 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('surveys_user_id_fkey'), 'surveys', 'users', ['user_id'], ['id'])
    op.drop_table('survey_members')
    # ### end Alembic commands ###
