"""add uq constraint to answer table

Revision ID: 86cc010863f0
Revises: 2ce4d1b4ef7e
Create Date: 2026-07-14 09:12:32.519415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cc010863f0'
down_revision: Union[str, Sequence[str], None] = '2ce4d1b4ef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_answer_response_question', 'answers', ['response_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_answer_response_question', 'answers', type_='unique')
    # ### end Alembic commands ###
