"""add uq constraint to responses table

Revision ID: 972cb02d0a10
Revises: 86cc010863f0
Create Date: 2026-07-14 09:17:53.423993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972cb02d0a10'
down_revision: Union[str, Sequence[str], None] = '86cc010863f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_response_survey_user', 'responses', ['survey_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_response_survey_user', 'responses', type_='unique')
    # ### end Alembic commands ###
